name: ncov-recombinant
channels:
  - bioconda
  - conda-forge
  - anaconda
  - defaults
dependencies:
  # Python
  - anaconda::python=3.9.10
  - anaconda::pip=22.0.3
  - anaconda::click=8.1.3
  - conda-forge::pandas=1.4.1
  # Workflow
  - bioconda::snakemake=7.3.6
  # Metadata and Sequence Manipulation
  - bioconda::csvtk=0.24.0
  - bioconda::seqkit=2.2.0
  # Alignmnent and Clade QC
  - bioconda::nextclade=2.5.0
  # Phylogeny
  - conda-forge::biopython=1.79
  # Visualization
  - conda-forge::seaborn=0.12.0
  - bioconda::snipit=1.0.7
  - plotly::plotly=5.10.0
  # Report Generation
  - conda-forge:python-pptx=0.6.21
  - bioconda::epiweeks=2.1.4
  - conda-forge::zip=3.0
  # For dev users
  #- conda-forge::pre_commit=2.17.0
  #- anaconda::git=2.35.0
  #- conda-forge::yarn
  - pip:
    # sc2rf dependencies
    - termcolor==1.1.0
    - tqdm==4.63.0
